# Generated by Django 5.1.3 on 2024-11-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle', models.JSONField()),
                ('solution', models.JSONField()),
                ('difficulty', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
