# Generated by Django 5.1.3 on 2024-11-29 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0002_cell_sessions_history_cell_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='sudoku_app.cell')),
            ],
        ),
    ]
