# Generated by Django 5.1.3 on 2024-12-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='pre_filled',
            field=models.BooleanField(default=False),
        ),
    ]
