# Generated by Django 5.1.3 on 2024-12-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0004_cell_pre_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='correct_move',
            field=models.BooleanField(default=False),
        ),
    ]
