# Generated by Django 5.1.3 on 2024-12-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0005_history_correct_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='notes',
            field=models.JSONField(default=list),
        ),
    ]
