# Generated by Django 5.1.3 on 2024-12-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_app', '0006_cell_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
